### ISSUE TITLE
watershed delineation

### ISSUE THREAD

**Issue by nmarzolf91** [MacroSHEDS/macrosheds#23]
Tried using `macrosheds::ms_delineate_watershed()` using lat/long from 2 sites and the following error was returned
![image](https://user-images.githubusercontent.com/37585374/173907341-ac9ad4db-7abd-4dc9-b4ea-b8b50187718b.png)

**Comment by vlahm** [comment]
the error message gives the solution! you need to run `whitebox::install_whitebox()`
