### ISSUE TITLE
ms_conversions double-checks 

### ISSUE THREAD

**Issue by westonslaughter** [MacroSHEDS/macrosheds#24]
@westonslaughter  is the "unable to convert to non-concentration variables" working perfectly? 
are sub-funcs such as convert_units getting sourced correctly?

both these threw issues on seemingly normal runs, need to make sure wasn't a user error on my part

**Comment by vlahm** [comment]
can you check on this one again, or close if you know it to be chill?

**Comment by westonslaughter** [comment]
this is indeed chill. closing.
