### ISSUE TITLE
download_ms_core_data needs quiet option

### ISSUE THREAD

**Issue by vlahm** [MacroSHEDS/macrosheds#3]
@spencerrhea @westonslaughter 

to suppress printing

**Comment by westonslaughter** [comment]
word. GH issues is lit.

**Comment by westonslaughter** [comment]
oh, also- Spencer and I were talking earlier about having this function be able to run with no parameters, where `download_ms_core_data()` will just download everything to the current directory- maybe with a stopgap print statement asking like, `this function will download the entire macrosheds dataset of {x}gb to the current directory- do you wish to proceed? (y/n/c)`

thoughts?

**Comment by vlahm** [comment]
that sounds good. with functions that prompt, it's always nice to provide a prompt = FALSE option too, so that people can use it non-interactively.
