### ISSUE TITLE
code review: mike vlah all comments (to be chunked into sub-issues)

### ISSUE THREAD

**Issue by westonslaughter** [MacroSHEDS/macrosheds#73]
@westonslaughter @ecogub

NOTES

some line numbers may be off, as i may have moved stuff around after listing them.

check git diffs. i made lots of changes

THINGS TO DISCUSS

do we need q_type to be an input parameter? that information is def contained in the var columns of q and chemistry.
i can't remember now why Spencer and I decided that was necessary in ms_calc_flux, but it sure seems superfluous now.

are output units correct? i see a lot of dividing by (1000area) in ms_internals.R, but shouldn't that be 1000000area to get from mg to kg? could totally be overlooking conversions happening elsewhere.

has it been verified that ms_calc_flux_rsfme produces the same outputs as the equivalent code in ecogub/RSFME? this is a must.

CHANGES AND COMMENTARY

The documentation needs to be updated. I changed the
tagline and description, but most of this appears to be identical to ms_calc_flux.
the new parameters need definitions, and the details and examples should be updated.
explain in the description (or in the parameter definitions where appropriate) that:
ms_interp == 1 values are automatically removed for rsfme methods
start_month for water years is hardcoded to 10 (Oct)
"good years" for Q are those with >= 311 days (i.e. approximately 85% coverage).
"good years" are defined differently for chem
if you're going to use the term "ideal method", explain that here. could use "Recommended"
anything else that doesn't go without saying!

more tests necessary in test_ms_calc_flux_rsfme. give it a very small but "dimensionally complete" test dataset,
e.g. two sites, two variables, maybe two months worth of observations. then you can run a dozen or so tests without
bogging down the overall test sequence (though you'll also have to make it run only the selected methods, rather than
running all and then filtering). we want to test not only the garden-variety runs
(q_type = 'discharge', method = 'rsfme'), but also the more obscure parameter options, like good_year_check
and method = . the tests don't have to be full-factorial, but they should cover a lot of ground.
This function is basically the keystone of MacroSheds, so let's make sure it's rock solid.

[line 94] is "simple" an rsfme method?

with glue, you can either include variables as in
x = 'b'; glue('a{x}c')
or
glue('a{x}c', x = 'b')
so constructs like this are redundant
x = 'b'; glue('a{x}c', x = x)

[103, 106, etc.] this construct is useful in like 30% of console messages:
paste(some_vector, collapse = ', ')
e.g.
print(glue('calculating flux using method(s): {m}', m = paste(method, collapse = ', ')))
instead of
print(glue('calculating flux using method(s): {m}', m = list(method))
which leaves junk characters

[105, etc.] writeLines is generally for writing to connections. just use print() for printing to console.
but maybe this is here with the intention to set up logging at a later date, in which case gg.

[112] i love the way you check whether RiverLoad is installed! haven't used find.packge before.

[114] instead of
if(class(x) == 'try-error')
use
if(inherits(x, 'try-error'))
which will work even if x has multiple classes.

[127] is "simple" both a method and an aggregation option? i think this is a vestige,
but please make sure.

[line 149] the following checks whether set x is a subset of y, but not the converse
if(all(x %in% y))
to check both at the same time, use
if(setequal(x, y))

[158-64] i'm stoked that this is set up to handle different sample frequencies! looks like heavy tweaking necessary
though to make this fully realized, like the join_distance for approxjoin and the number of days in a good year.
of course we don't need that now.

daterange on line 237 and chunk_daterange on 345 are determined on the chemistry dataset.
should it be determined instead on the discharge dataset,
which might extend beyond chemistry by a few weeks and still be informative? you could filter the q set so that it extends
beyond chem by at most x weeks in either direction.

[280-333] zomg, this fully replaces ms_calc_flux! that's great! let's get rid of that function and rename this one ms_calc_flux
(since even i still can't remember what rsfme stands for). that will require further updating the function documentation at
the top. also, Wes, I think you added the ws_area_scaled parameter to ms_calc_flux. probably that should be ported over,
as currently method "simple" yields unscaled flux, whereas all other methods yield area-scaled flux (right?).
Let's get rid of that acronym wherever possible, like in the error text on line 70 and even the argument to method.
How about "all"?

instead of [280]
if('simple' %in% method)
and separately [688]
if(any(method == 'simple'))
can we add some handling right at the start so that the user knows what they're getting? i.e. if they
specified method = c('simple', 'rsfme'), they're already confused. we need to indicate unequivocally that "simple" means
daily flux is returned, and all the other methods are governed by "aggregation". the clearest design would
issue an error if method = 'simple' and aggregation = 'monthly' or 'yearly'. that would mean the default for aggregation
would be NULL. likewise, if method = 'rating' and aggregation isn't specified, there would be an error stating "aggregation must
be specified when method is 'rating'". errors are good, especially for the manual-averse.
ideally, they guide users toward proper usage.

this comment seems like something you were going to come back to:
# this is the step where concentration value errors turn to NA

in mean_or_x, you're taking the mean of the variance. probably this would cause chaos if we weren't on a daily timestep.
this function seems to be based on sd_or_0 in data_processing/src/global/global_helpers.R, but see how that function is used
elsewhere in global_helpers.R. probably that implementation could help with any NA error values youre seeing re: comment above.

[441, 448] flag_df is never used again.

[467-473] it looks like you meant to carry on with separate dataframes, two with uncertainty and two without,
but con_target_year and q_target_year are never used again, and chem_df_errors and q_df_errors are immediately reassigned
to chem_df and q_df. RAM is not happy! there's actually a ton of reassignment going on around this area, and while
new variable names can sometimes improve clarity, here they detract from it, while spamming memory
(which wouldn't be an issue in Python, which binds variables by reference, but totally is for R with its
variable copying behavior). this will become an issue at higher sample frequencies than daily.

[486, 495] grouping by water year shouldn't be necessary here, since we're operating on raw_data_target_year

[540] probs should be an error

[590, 591] did you guys decide to use log10() rather than log() for a reason? it doesn't really matter, but
scientists are almost always talking about natural logs when they just say "log". i think USGS digs log10,
which is chill.

[619] will the user know what "ideal method" means? (see documentation suggestions above)
You use "ms_recommended" elsewhere. "Recommended" seems fine.

[removed on ~619 etc.] i've seen ungroup() used on a lot of dataframes that aren't grouped to begin with.
this function should only only be meaningful if it follows group(). have you found another way to use it?

[627-628] this warning is written as if from the perspective of the program. the following rephrase
would make it clearer to a human unfamiliar with the function internals:
"The composite method would be recommended by Aulenbach et al. 2016 for at (),
but that method results in illegal values. Using period-weighting instead."
Please look over the other messages and make clarifications like this where possible.

[682, 684] def only run the methods that have been requested. the core methods on 504-525 should
all be run conditionally, depending on the value of methods, and the code that follows should
be flexible enough to handle any combination.

[691-695] some of these TODOs are essential. 5th for sure. 1st too, because it will make you think about
organization and efficiency.

removed junk code at the bottom, after the function definition

i get a wall of "length mismatch" warnings when i run
ms_flux <- ms_calc_flux_rsfme(chemistry = chemistry, q = q, q_type = 'discharge',
method = 'average', aggregation = 'monthly')
using the input data from test_ms_calc_flux_rsfme.R. That warning is usually problematic.
If it's not in this case, it should be suppressed as it will make every user run for the hills.

**Comment by vlahm** [comment]
regarding that last one, i actually get a different number of warnings each time (been rerunning package tests). very strange!
